Implemented basic keyboard
0xFEEDC0DE64/esp-gui-lib pull request #18
Opened 2022-06-13 16:03 UTC by CommanderRedYT

2022-06-13 16:03 UTC, CommanderRedYT commented
ToDo: Fix vertical mode

2022-06-13 16:04 UTC, CommanderRedYT commented
@0xFEEDC0DE64 Can you review everything now so that I can fix everything and fix vertical mode at the same time?

2022-06-14 09:22 UTC, 0xFEEDC0DE64 requested changes

2022-06-14 09:22 UTC, 0xFEEDC0DE64 commented on src/changevaluedisplay.cpp
> +    }
use my float text renderer

2022-06-14 09:22 UTC, 0xFEEDC0DE64 commented on src/changevaluedisplay.cpp
> +    }
(ok refactoring is huge, do it in the next pull request)

2022-06-14 09:22 UTC, 0xFEEDC0DE64 commented on src/changevaluedisplay_chrono.h
> +    }
saaaaaimme

2022-06-14 09:22 UTC, 0xFEEDC0DE64 commented on src/keyboardhelper.h
> +    }
wenn impl schon im header sein muss, dann zumindest bitte unter der klasse und nicht inline in der klasse. macht zb größe abschätzen unmöglich ohne millionen zeilen zu lesen

2022-06-14 11:56 UTC, 0xFEEDC0DE64 approved these changes

2022-06-14 11:56 UTC, 0xFEEDC0DE64 commented on src/keyboardhelper.h
> +#include <futurecpp.h>
futsch oida

2022-06-14 11:56 UTC, merged